Beer.destroy_all
Food.destroy_all

Food.create(dish: 'The Trio', description: 'Snacks')
Food.create(dish: 'Pretzel Bites and Beer Cheese Queso', description: 'Snacks')
Food.create(dish: 'Cheese Board', description: 'Snacks')
Food.create(dish: 'Flatbread and Hummus', description: 'Snacks')
Food.create(dish: 'White Cheddar Mac n Cheese', description: 'Snacks')
Food.create(dish: 'Nachos', description: 'Snacks')
Food.create(dish: 'Soupe of the day', description: 'Snacks')
Food.create(dish: 'Cheese', description: 'Pizza')
Food.create(dish: 'Pepperoni', description: 'Pizza')
Food.create(dish: 'Sausage and Pepperoni', description: 'Pizza')
Food.create(dish: 'Deluxe', description: 'Pizza')
Food.create(dish: 'BBQ Chicken', description: 'Dillas')
Food.create(dish: 'Buffalo Chicken', description: 'Dillas')
Food.create(dish: 'Carnitas', description: 'Dillas')
Food.create(dish: 'Chicekn Fajitas', description: 'Dillas')
Food.create(dish: 'BBQ Pulled Pork', description: 'Sandwiches')
Food.create(dish: 'Meatball Grinder', description: 'Sandwiches')
Food.create(dish: 'Black Bean w/ Tzatziki', description: 'Sandwiches')

Beer.create(name: 'Bobcat Lager', style: 'Lager', alcohol: '4.9%', ibu: 17, description: 'A crisp but bold lager with a perfect blend of malts and hops to provide that down-under experience.')
Beer.create(name: 'Black Bear', style: 'Milk Stout', alcohol: '7%', ibu: 19, description: 'A very rich and smooth stout with tapered hops which allows for a creamy roasted malt experience. This brew contains Lactose.')
Beer.create(name: 'Black Fox', style: 'Oatmeal Stout', alcohol: '4.6%', ibu: 27, description: 'A stout with great malt and oat flavor without the heavy stout body. This beer has the right blend of malts, oats and hops for all to enjoy.')
Beer.create(name: 'Red Fox', style: 'Irish Red Ale', alcohol: '5.3%', ibu: 20, description: 'A blend of captivating malts, providing a rust-red color, which are not overtaken by hops. There is plenty of body but yet a crisp refreshing beer. This beer is a friend/family favorite.')
Beer.create(name: 'Nuthatch Brown', style: 'English Brown Ale', alcohol: '6.5%', ibu: 26, description: 'A brown ale that allows the caramel and chocolate malt flavors to rise without being overtaken by hops. A great winter or summer brew, that goes great with many foods.')
Beer.create(name: 'Eagle Light', style: 'Light Lager', alcohol: '3.2%', ibu: 11, description: 'A German pilsner with caramel malt flavors. A light refreshing Lager with much more flavor to offer than your domestic light beers!')
Beer.create(name: 'Rattlesnake', style: 'IPA', alcohol: '6.5%', ibu: 40, description: 'The right blend of bittering hops that allows the aroma and flavor of the base malt and hint of lime to please your pallet, then finishes off with a trio of hops flavors. This IPA surprisingly appeals to both non-IPA and IPA lovers.')
Beer.create(name: 'Blonde Bear', style: 'Blonde Ale', alcohol: '6.2%', ibu: 18, description: 'A backbone of stellar malts with a fresh biscuit flavor. A great brew for any time of year.')